version: "2"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
